name: 'MongoDB for GitHub Actions'
description: 'Start a MongoDB server with configurable options'

branding:
  icon: 'database'
  color: 'green'

inputs:
  mongodb-version:
    description: 'MongoDB version to use (default "latest")'
    required: false
    default: 'latest'

  mongodb-replica-set:
    description: 'MongoDB replica set name (no replica set by default)'
    required: false
    default: ''

  mongodb-port:
    description: 'MongoDB port to use (default 27017)'
    required: false
    default: 27017

  mongodb-root-username:
    description: 'MongoDB root username (default empty)'
    required: false
    default: ''

  mongodb-root-password:
    description: 'MongoDB root password (default empty)'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.mongodb-version }}
    - ${{ inputs.mongodb-replica-set }}
    - ${{ inputs.mongodb-port }}
    - ${{ inputs.mongodb-root-username }}
    - ${{ inputs.mongodb-root-password }}
