name: Start MongoDB Server

on: [push, pull_request]

jobs:
  mongodb-action:
    name: Start MongoDB Server v${{ matrix.mongodb-version }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.0', '4.2', '4.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MongoDB Server
        uses: ./
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
