name: Single Instance Tests

on: [push, pull_request]

jobs:
  single-instance-on-default-port:
    name: MongoDB v${{ matrix.mongodb-version }} on default port

    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.0', '4.2', '4.4', '5.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MongoDB Server v${{ matrix.mongodb-version }}
        uses: ./
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test ./test/single-instance.js

  single-instance-with-credentials:
    name: MongoDB v${{ matrix.mongodb-version }} on default port with credentials

    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.0', '4.2', '4.4', '5.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MongoDB Server v${{ matrix.mongodb-version }}
        uses: ./
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-root-username: admin
          mongodb-root-password: admin

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test ./test/single-instance.js
        env:
          MONGODB_USERNAME: admin
          MONGODB_PASSWORD: admin

  single-instance-on-custom-port:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.0', '4.2', '4.4', '5.0']

    name: MongoDB v${{ matrix.mongodb-version }} on custom port
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MongoDB Server v${{ matrix.mongodb-version }}
        uses: ./
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-port: 12345

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test ./test/custom-port.js
        env:
          MONGODB_PORT: 12345

  single-instance-on-custom-port-with-credentials:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['4.0', '4.2', '4.4', '5.0']

    name: MongoDB v${{ matrix.mongodb-version }} on custom port with credentials
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start MongoDB Server v${{ matrix.mongodb-version }}
        uses: ./
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-port: 12345
          mongodb-root-username: admin
          mongodb-root-password: admin

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test ./test/custom-port.js
        env:
          MONGODB_PORT: 12345
          MONGODB_USERNAME: admin
          MONGODB_PASSWORD: admin
